### ISSUE TITLE
can u plz tell how to install

### ISSUE THREAD

**Issue by Ankit2230** [rishav394/VIT-Proxy-Chrome-Extension#1]
detail what are the steps

**Comment by rishav394** [comment]
Please checkout the Readme. https://github.com/rishav394/VIT-Proxy-Chrome-Extension#how-to-build

**Comment by Ankit2230** [comment]
hi
bro i read that but not able to install can plz send proper steps like what
is yarn built and then run compiler
can u plz make a video how to install that will really helpful .

Ankit

**Comment by rishav394** [comment]
You can get the extension without building from [here](https://chrome.google.com/webstore/detail/vit-proxy/ndnkgfgcodefniaancaggnnmnecbgedo).

**Comment by Ankit2230** [comment]
do i need to buy it ?

**Comment by rishav394** [comment]
Unless you are planning to build from source and to prevent leaching, Yes.
